EnablePrimaryMouseButtonEvents(true)
function OnEvent(event, arg)
	if (event == "MOUSE_BUTTON_PRESSED" and arg==1 and IsKeyLockOn("capslock") and IsKeyLockOn("numlock")==false  and IsKeyLockOn("scrolllock")==false) then--R-99
		--ReleaseMouseButton(2)
		--PressMouseButton(1)
		Sleep(10)	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,4)--2
			Sleep(60)
		end	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,4)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(1,2)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,5)
			Sleep(60)	
		end		
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,7)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-6,7)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,6)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,5)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,7)--10
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,5)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(1,7)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(4,4)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,6)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,4)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,1)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,1)
			Sleep(60)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,1)--18
			Sleep(60)	
		end
		elseif (event == "MOUSE_BUTTON_PRESSED" and arg==1 and IsKeyLockOn("capslock") and IsKeyLockOn("numlock") and IsKeyLockOn("scrolllock")==false) then--flatline
		--ReleaseMouseButton(2)
		--PressMouseButton(1)
		Sleep(50)	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(1,11)--2
			Sleep(100)
		end	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(0,3)
			Sleep(100)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,8)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,4)
			Sleep(100)
		end		
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,4)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(1,5)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-4,-1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,-1)--10
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,3)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,4)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,2)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(5,1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(1,2)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,0)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,-1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(4,5)--18
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(4,5)--19
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(4,5)--20
			Sleep(100)
		end
	elseif(event == "MOUSE_BUTTON_PRESSED" and arg==1 and IsKeyLockOn("capslock") and IsKeyLockOn("numlock")  and IsKeyLockOn("scrolllock")) then--spitfire
		--ReleaseMouseButton(2)
		--PressMouseButton(1)
		Sleep(50)	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,7)--2
			Sleep(100)
		end	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(1,2)
			Sleep(100)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(5,4)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(4,7)
			Sleep(100)
		end		
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,5)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(1,5)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,2)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-5,-1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,-1)--10
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,5)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,2)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(6,4)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,2)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(6,-1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,3)--18
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,3)--19
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,4)--20
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(6,1)--21
			Sleep(100)
		end	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,0)--22
			Sleep(100)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(1,1)--23
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,0)--24
			Sleep(100)
		end		
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,2)--25
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,2)--26
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,1)--27
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,-2)--28
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,2)--29
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-4,3)--30
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,3)--31
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-4,-2)--32
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-4,-1)--33
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,2)--34
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(0,3)--35
			Sleep(100)
		end
	elseif(event == "MOUSE_BUTTON_PRESSED" and arg==1 and IsKeyLockOn("capslock") and IsKeyLockOn("numlock")==false and IsKeyLockOn("scrolllock") ) then
		--ReleaseMouseButton(2)
		--PressMouseButton(1)
		Sleep(50)	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,10)--2
			Sleep(100)
		end	
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,6)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,6)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(0,6)
			Sleep(100)
		end		
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,4)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(0,3)
			Sleep(100)	
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,2)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-3,3)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-1,3)--10
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,0)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(-2,2)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(2,2)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(3,3)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(4,0)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(5,-1)
			Sleep(100)
		end
		if(IsMouseButtonPressed(1))then
			MoveMouseRelative(5,1)--18
			Sleep(100)
		end
	end
end